title: Learning Rust
subtitle: "Rust Programming Language Tutorials"
description: "Rust Programming Language Tutorials"
author: Dumindu Madunuwan
language: en
timezone: UTC

url: https://org.github.io
root: /

theme: navy

deploy:
  type: git
  repo: git@github.com:org/org.github.io.git

highlight:
  enable: false

hljs:
  enable: true

google_analytics: UA-XXXXXXXXX-1
algolia:
  en:
    api_key: xxxxxx
    index_name: xxxxxx
github: org/site
